<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Menu | Pizza Hut</title>
		<link rel="stylesheet" type="text/css" href="pizza.css"/>
	</head>
	<body>
			<?php
				include("common.php");
				head();
			?>
				<div id="menubody">
				<br>
					<div id="menu"><img src="images/pmenu.jpg" width="750px"></div>
					<br>
				</div>
			<?php
			foot();
			?>
	</body>
</html>